# Generated by Django 5.0.6 on 2024-05-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("user_id", models.CharField(max_length=200)),
                ("contents", models.TextField()),
                ("title", models.CharField(max_length=200)),
                ("picture", models.ImageField(upload_to="")),
                ("picture_id", models.IntegerField()),
            ],
        ),
    ]
