# Generated by Django 5.0.6 on 2024-06-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "comment_id",
                    models.AutoField(
                        auto_created=True,
                        db_column="comment_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("content", models.TextField(db_column="content", default="0")),
            ],
            options={
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="Love",
            fields=[
                (
                    "love_id",
                    models.AutoField(
                        db_column="love_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "love",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "picture_id",
                    models.AutoField(
                        auto_created=True,
                        db_column="picture_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=200)),
                ("image", models.BinaryField(db_column="image", editable=True)),
                ("content", models.TextField(db_column="content", default="0")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, db_column="created_at"),
                ),
            ],
            options={
                "db_table": "picture",
            },
        ),
    ]
