# Generated by Django 5.0.6 on 2024-05-23 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "picture_id",
                    models.IntegerField(
                        db_column="picture_id", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=200)),
                ("image", models.BinaryField(db_column="image", null=True)),
                ("content", models.TextField(db_column="content", default="0")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, db_column="created_at"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "picture",
            },
        ),
        migrations.CreateModel(
            name="Love",
            fields=[
                (
                    "love_id",
                    models.IntegerField(
                        db_column="love_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "picture_id",
                    models.ForeignKey(
                        db_column="picture_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gallery.picture",
                    ),
                ),
            ],
            options={
                "db_table": "love",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "comment_id",
                    models.IntegerField(
                        auto_created=True,
                        db_column="comment_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                ("content", models.TextField(db_column="content", default="0")),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "picture_id",
                    models.ForeignKey(
                        db_column="picture_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gallery.picture",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
            },
        ),
    ]
