# Generated by Django 5.0.6 on 2024-05-18 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="picture",
            options={"managed": False},
        ),
    ]
