# Generated by Django 5.0.6 on 2024-05-18 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0002_alter_picture_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="picture",
            table="picture",
        ),
    ]
