# Generated by Django 5.0.6 on 2024-05-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0002_alter_picture_image_alter_picture_picture_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture_id",
            field=models.AutoField(
                auto_created=True,
                db_column="picture_id",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
