# Generated by Django 5.0.6 on 2024-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0003_alter_picture_picture_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.AutoField(
                auto_created=True,
                db_column="comment_id",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
