# Generated by Django 5.0.6 on 2024-05-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0003_alter_picture_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "picture_id",
                    models.ForeignKey(
                        db_column="picture_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gallery.picture",
                    ),
                ),
            ],
        ),
    ]
