# Generated by Django 5.0.6 on 2024-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0004_alter_comment_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="love",
            name="love_id",
            field=models.AutoField(
                db_column="love_id", primary_key=True, serialize=False
            ),
        ),
    ]
