# Generated by Django 5.0.6 on 2024-05-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0004_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="Love",
            fields=[
                (
                    "love_id",
                    models.IntegerField(
                        db_column="love_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="created_at"),
                ),
                (
                    "picture_id",
                    models.ForeignKey(
                        db_column="picture_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gallery.picture",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
