# Generated by Django 5.0.6 on 2024-05-21 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0005_alter_comment_options_love"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comment",
            table="comment",
        ),
    ]
