# Generated by Django 5.0.6 on 2024-05-21 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Gallery", "0006_alter_comment_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="love",
            options={"managed": False},
        ),
    ]
